#!/usr/bin/env python
''' Command Line Interface for tract_merge '''
import argparse
from streamlines.cli.streamlines_merge import streamlines_merge

if __name__ == "__main__":

    # Parser
    parser = argparse.ArgumentParser(description=("merges tracts"))

    parser.add_argument('tracts_to_merge', type=str, nargs='+')

    parser.add_argument('outfile', type=str)

    args = parser.parse_args()

    streamlines_merge(args.tracts_to_merge, args.outfile)
